<?php

namespace App\Http\Controllers;

use App\Models\Activity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;

class ActivityController extends Controller
{

    public function index(){
        // au=audience_id, a=activity, c=campaign_id, e=event_id

        $activities_array=["v"=>"viewed", "c"=>"clicked", "d"=>"downloaded",];

        $rules = [
            'au' => ['required|string', Rule::exists('audiences', 'id')],
            'c' => ['required|string', Rule::exists('campaigns', 'id')],
            'a' => ['required|string'],
            'e' => ['required|string', Rule::sexists('events', 'id')],
            'r'=>[Rule::requiredIf($activities_array[request()->query('a')]=="c")],
        ];


        // activities


        $validator = Validator::make(request()->all(), $rules);
        if ($validator->fails()) {
            return response()->json(['errors' => $validator->errors()], 422);
        }
        $data=request()->all();
        $headers=request()->headers->all();
        $ip=request()->ip();
        $user_agent=request()->userAgent();
        $audience_id=request()->query('au');
        $activity=request()->query('a');
        $event_id=request()->query('e');
        $redirect_url=request()->query('r');
             //

        // check if audience_id, activity and event_id are valid

        $info=["data"=>$data, "headers"=>$headers, "ip"=>$ip, "user_agent"=>$user_agent];
        Activity::create([
            "audience_id"=>$audience_id,
            "event_id"=>$event_id,
            'activity'=>$activity,
            "data"=>json_encode($info)
        ]);

        if($activities_array[$activity]=="viewed"){
            return response('',200)->setContent(base64_decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/D/PwAHAwL/qGeMxAAAAABJRU5ErkJggg=="))->header('Content-Type', 'image/png');
        }
        if($activities_array[$activity]=="clicked"){
            return response()->away($redirect_url);
        }
        if($activities_array[$activity]=="viewed"){
            return response('Generated by rephish',200)->header('Content-Type', 'text/plain');
        }
        return response('',200)->setContent(base64_decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z/D/PwAHAwL/qGeMxAAAAABJRU5ErkJggg=="))->header('Content-Type', 'image/png');

    }

}
